//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// admin_main class.
/// </summary>
/// <remarks>
/// Auto-generated class.
/// </remarks>
public partial class admin_main {
    
    /// <summary>
    /// Master property.
    /// </summary>
    /// <remarks>
    /// Auto-generated property.
    /// </remarks>
    public new layout_Admin_layout Master {
        get {
            return ((layout_Admin_layout)(base.Master));
        }
    }
}
