//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// ContactUs class.
/// </summary>
/// <remarks>
/// Auto-generated class.
/// </remarks>
public partial class ContactUs {
    
    /// <summary>
    /// Master property.
    /// </summary>
    /// <remarks>
    /// Auto-generated property.
    /// </remarks>
    public new TTS.layout.layout_MasterPage2 Master {
        get {
            return ((TTS.layout.layout_MasterPage2)(base.Master));
        }
    }
}
