//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTS_WA {
    
    
    public partial class PageNotFound {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new TTS.layout.layout_MasterPage2 Master {
            get {
                return ((TTS.layout.layout_MasterPage2)(base.Master));
            }
        }
    }
}
