set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[Load_Products]
	/*
	(
	@parameter1 int = 5,
	@parameter2 datatype OUTPUT
	)
	*/
AS
	/* SET NOCOUNT ON */ 

insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('100 Math Activities Kids Need to Do  By 1st Gr','439566797',7.99,'100 Math Activities kids by 1st',20,'Scholastic Math Workbook/ Activity Book (224 pages)')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('100 Math Activities Kids Need To Do By 3rd Grade','0439566819',7.99,'100 Math Activities Kids...by 3rd Grade',18,'Continuing the successful Scholastic `100` workbook series, this product provides 100, full-color, full-spread math activities that kids need to cover by and in third grade. 224 pages')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('100 Math Problems Kids Need to Do by 1st Grade','0439669669',2.49,'100 Math Problems Kid by 1st grade',6,'Skill-specific units that have everything you need to introduce reading.  Reproducibles provide important practice.  An answer key and Teacher`s Guide with activites are also included.  The convienient folder lets you store the unit for future use.')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('100 Math Problems Kids Need to Do by 2nd Grade','0439669677',2.49,'',6,'Simple addition and subtraction, regrouping, adding 3 numbers, adding.subtracting 2 digit numbers, adding/subtracting 3 digit numbers - Fun, full-color stickers ')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('100 Words Kids Need to Read by 1st Grade','0439669626',2.49,'100 Words by 1st grade good.jpg',6,'Exciting new reading/workbook series that help develop the skills that make reading fluent and fun!')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Addition & Subtraction Puzzle Cards','',2.99,'Add & Sub Puzzle Cards jpg',null,'A selected mix of double sided addition and subtraction puzzle cards.  20 Two-part puzzle pieces')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Alphabet File Series','0742428486',3.49,'Alphabet file series jpg',7,'Alphabet flash cards are divided into two sets: 26 uppercase alphabet cards and 26 lowercase alphabet cards. Each card represents a letter of the alphabet. On the reverse side of the card is a picture representing that letter of the alphabet')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Alphabet Puzzle Cards','LSP0431S',2.99,'Alphabet Puzzle Cards.JPG',7,'Phonics Puzzle Cards will reinforce letter recognition, beginning letter sounds, word families and spelling. ')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Astronomy Cards','156189690X',2.99,'Astronomy Cards jpg',7,'54 fun-filled flash cards include: captivating color photos of the planets, fasinating facts about the planets, starts, constellations and galaxies, bonus cards featuring famous astronauts, astronomers and U.S. space programs')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Basic First Grammar 6th Grade','0867349824',3.75,'Grammar 6th grade',6,'The basics of these skills include reading comprehension and a working knowledge of gammar and spelling.  30 page book includes answer key')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Be Boy Buzz  by Bell Hooks','0786816430',4.99,'Be Boy Buzz',9,'Famed author Bell Hooks brings us a tight, exuberant story that captures the essence and energy of what it means to be a boy. Chris Raschkas soulful illustrations buzz with a force that is the perfect match for these powerful words.')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Beginning Blends Puzzle Cards','',2.99,'Blend Cards jpg',null,'Double sided cards will allow you to match blends to word families and identify blends in sentences.  20 Two-part self correcting cards')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Celebration Centers','865304149',8.99,'Celebration Centers.jpg',14,'Centers that celebrate holidays.  Skills-based activites, crafts, food, puzzles to help your child learn and grow.')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Cheerios','',4.99,'',10,'On every page, there are pictures that need to be completed by adding Cheerios to just the right places. (No milk, please!) Teddies need Cheerios buttons, mice need Cheerios glasses, and fish need Cheerios bubbles. Board Book Prek-1')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Division Flash Cards','',1.99,'',6,'Division Flash Cards by Crayola ')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Earth Science at School K-2','0768225035',3.75,'Earth science at school K-2 jpg',6,'This book includes six units, including activities and worksheets, that each focus on a particular part of the school environment.  Through reading comprehension exercises, hands-on activities and projects, written and art exercises, and more, earth science becomes an enjoyable and rewarding part of your classroom curriculum.  Students will discover interesting facts about planets, fossils, and plants in these enriching lessons.  Using the scientific process skills such as observing, communicating, making models, and drawing conclusions, the individual and small group activities help students discover earth science in one of the most familiar places to children today-the school.')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Elementary Economics','5146805180',3.5,'Post later',7,'Basic Skills Hands-on Activities for Teaching Fundamental Economic Skills')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('File Folder Addition Game','FFADD',1.99,'ffaddinside',5,'Teacher created material:  Laminated board and pieces. Solve the problem by placing the correct answer on the picture. File color may vary.')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('File Folder Sequencing Numbers','FFSEQ',1,'File Folder Sequencing jpg',5,'Complete the train by sequencing numbers in order.  Dry erase marker is not included and color of file folder may vary.')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('File Folder Subtraction Game','FFSUB',1.99,'ffsubtractinside',5,'Teacher created material:  Laminated board and pieces. Solve the problem by placing the correct answer on the picture.  File color may vary.')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('First Words','773000913',1.99,'First Words Flash Cards.jpg',6,'First Words Flash Cards help to teach preschoolers associations between familiar objects and words.  Each card features a colorful object with the corresponding object name on the back of the card.  There are 36 cards and each one is approx. 3x5 inches.  Stickers are included.')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Getting Ready To Teach 2nd Grade by Kimberly Seto','768202655',5.99,'Getting ready to teach 2nd.jpg  (Z drive)',10,'First-time teachers of second grade, here is a practical handbook created especially for you.    This book will guide you through the joys and anxieties of teaching a new grade. An overview of the 2nd Grade curriculum Activities designed to bring the curriculum to life Planning, record-keeping, and assessment strategies 13 reproducible pages')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Graphing File Folder','GFF100',1,'Sorting Nuts jpg',5,'Fill-in graph to match the picture.  Dry erase marker not included.')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Hershey`s Kisses Addition Book','0439241730',3.99,'Hershey`s Addition book',6,'What better way to introduce simple addition concepts than with delicious Hershey¹s Kisses? To illustrate math concepts, this book features a cast of miniature clowns struggling under the weight of life-sized Hershey¹s Kisses. ')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Leap Frog Memory Mate','047754307306',5.99,'Memory Mate jpg',22,'Picture-to-picture matching and bilingual words provide a grow-with-me format.  The unique locking system allows the child to match confidently.  Includes: 90 Spanish/English interlocking Memory Mate Cards and parent guide and instruction book.  For ages 3+')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Learn to Tell Time Write On','1897280327',1.99,'Learn to Tell Time Write On.jpg',8,'Learn To Tell Time - Write On Wipe Off  w/ Dry Erase Marker This board and booklet provide a fun and effective format to help your children learn to tell time.')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Lessons of Faith for Kids','32927729356L',2.99,'Lessons of Faith',6,'(8) Childrens Devotionals  (With CD)')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Little Math Stories','768200156',6.99,'Little Math Stories.jpg',8,'Build literacy with beginning readers by inviting them to make their own books! Charming stories will delight young readers with simple, repetitive, and predictable text, rhyme, rhythm, counting and motivating illustrations.  ')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Little Science Stories','0768200164',3.75,'',7,'Build literacy with beginning readers by inviting them to make their own little science books! Children are actively engaged as they create their own illustrations and complete sentence frames, making the books truly their own.  There are 10 readers.')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Martin Luther King Jr. File Folder Game','MLK100',1.99,'MLK Inside jpg - Ebay Pictures',5,'Match colors (red, black, blue, green, yellow, brown, white and orange) to MLK profile.  This game will help with identifying colors and reading color words.  This teacher created game includes 8 games pieces.')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('My Spanish Book of Words  Mi libro de las palabras en espanol e ingles','1403730555',5.99,'',null,'My Spanish Book of Words engages children with vibrant photograpgs of familiar objects and actions.  This bilingual book builds vocabulary in Spanish and English.')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Name Tags','',1.5,'',4,'Size: 3.375" x 7.75" Self-Adhesive 36 Count')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Nursery Rhymes File Series','074242877X',3.49,'Nursery Rhymes file series',7,'54 fun-filled flash cards feature: Reinforcement in phonics, uppercase and lowercase letter recognition, and reading readiness skills Charming, full-color illustrations that engage children A special card that offers creative games designed to reinforce learning ')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Parables of Jesus','32927729356P',2.99,'Parables of Jesus',6,'(8) Childrens Devotionals  (With CD)')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Parts of Speech Grade 2  ***','0742418529',3.5,'Parts of Speech gr 2 bmp.',5,'Learning to identify and correctly use the parts of speech is an essential language and reading skill. Parts of Speech helps students identify and use the right parts of speech: nouns, verbs, adjectives, adverbs, prepositions, pronouns, interjections, and conjunctions. In addition to essential practice in parts of speech, the reproducible worksheets offer practice in sentence structure and word order. Parts of speech are fundamental elements of communication and appear in most standardized tests. Parts of Speech provides a variety of question formats to help strengthen students` test-taking skills. Questions include multiple choice and short written answers. The sequential activities introduce cross-curricular topics that fit into every classroom. Pages: 48')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Parts of Speech Grade 4','0742418545',3.5,'Parts of Speech gr 4 jpg',6,'Learning to identify and correctly use the parts of speech is an essential language and reading skill. Parts of Speech helps students identify and use the eight parts of speech: nouns, verbs, adjectives, adverbs, prepositions, pronouns, interjections, and conjunctions.')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('PowerThink - Critical Thinking Activities','0768204186',3.5,'PowerThink gr 2jpg',8,'PowerThink is full of cooperative activites that encourage students to evaluate information, differentiate between fact and opinion, and look at both sides of an issue.  Working in small groups, students will have an opportunity to practice a variety of important skills.  Second grade level.')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Rhyming Stories - Paper Plate Phonics Book 3','WBW1914',4.99,'Take picture',7,'This interactive workbook provides the student with hands on activities for exposure to rhyming stories')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Scholastic Student Thesaurus','0439248825',8.99,'Scholastic Student Thesuarus',23,'Thesaurus for students ages 9-12')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Scholastic Student Thesaurus','0439248825',9.99,'Thesaurus jpg',null,'Any young student should find this intuitive, well-designed thesaurus quite helpful, as well as useful, practical, handy, beneficial, and versatile.  If you have an aspiring wordsmith on your hands--or just a kid who`s renowned for his prolific deployment of the words nice and okay--this 204-page thesaurus offers well over 1,000 primary entries and more than 10,000 supplementary entries using a clever on-the-page index. Instead of a traditional index, the Scholastic Student Thesaurus lists supplemental entries alphabetically on every single page.  Each entry also contains part-of-speech labels, and many include usage notes and other synonym and antonym cross-references.  For ages 10+')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('School Days Key Chain','KC100',2,'200802170002.JPG',4,'Key Chain')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('School House Sweat Shirt','',13.99,'School House Sweat Shirt jpg',20,'Navy Blue Teacher Style Sweat Shirt.  ')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('School Paper Clips','PC100',1.99,'Paper Clips.JPG',5,'Four "School Style" Paper Clips ')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('School Photo Cards','PIXCARD',1.99,'School Photo Cards jpg',4,'')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Short Apron Black','APRONBLK',null,'Apron Short Blk Good',7,'Three-Pouch Pocket 65% polyester, 35% cotton (natural 100% cotton canvas)')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Short Apron Red','APRONRED',null,'Short Apron Red jpg',7,'Three-Pouch Pocket 65% polyester, 35% cotton (natural 100% cotton canvas)')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Skin Again  by Bell Hooks','078680825X',9.99,'Skin Again',18,'This hardcover book celebrates all that makes us unique and different.  It offers new ways to talk about race and identity.  Demensions: 10.6 x 9.3 x 0.5')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Sleepy Hollow','',null,'',null,'')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Sound Alike Puzzle Cards','',7.99,'base_media(1)jpg',22,'Homophones - 30 Self Matching Puzzles')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Spanish Picture Dictionary','Order from teacherwide',8.99,'',null,'This delightfully illustrated bilingual dictionary features a variety of Disney Standard and Classic characters who introduce children to the Spanish language. Organized thematically, children will learn vocabulary, pronunciation, spelling, and usage for each featured word. Over 1,000 entries written in neutral Spanish, accompanied by native language translation. K-2')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Spelling Wipe Off Cards','8895840360',1.99,'200802150002.JPG',6,'')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Spinner','Spin100',1,'Spinner jpg',2,'Colorful 5 Space Spinner')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Teacher Memo Pad','TCHMEMO',1.99,'Teacher Memo Pad jpg',null,'Teacher Memo Pad with sheets')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Teacher`s Rule T-Shirt','TS100XL',8,'Black T Teachers Rule Good.jpg',10,'Black Teacher`s Rule T-shirt with gold writing.  The shirt is made by Jerzees and it is 50% cotton and 50% polyester.   Sizes available: x-large  ')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Tutors Handbook - Math 6th Grade','0768206650',5.99,'Tutor`s Handbook jpg',8,'This book offers a variety of activites to help you create tutoring sessions that are both fun and educational.  Dozens of ideas are included in this handbook to help students learn to enjoy math.   ')
insert into Product (sProdName, sItemNo,dPrice, sImageName,iWeight, sLongDesc) values('Word Cards - 1','SW100',1,'',3,'Teacher Created 15 Pre-Primer Sight Word Cards ')
	
	RETURN

 